"""Compatibility surface for the chat-op grammar (issue #1764).

The grammar itself — the pydantic arg models, the op-name registry, and
``parse_tool_call`` — moved verbatim to :mod:`src.ops.grammar`, next to
the operation registry (:mod:`src.ops.registry`) that maps every chat op
onto its canonical executor. This module re-exports the whole surface so
existing importers (``src.ai.chat``, the contract tests, and anything
external) keep working unchanged; what the model emits and what the web
client validates against is byte-identical.
"""

from __future__ import annotations

from src.ops.grammar import (
    _OP_REGISTRY,
    Alignment,
    ApplyPatchArgs,
    ApplyPatchOp,
    CreateCollectionArgs,
    CreateCollectionOp,
    CreateScheduleArgs,
    CreateScheduleOp,
    DayPattern,
    DeleteLineOp,
    DeleteScheduleArgs,
    DeleteScheduleOp,
    DisablePluginArgs,
    DisablePluginOp,
    EnablePluginArgs,
    EnablePluginOp,
    InsertLineOp,
    InstallPluginArgs,
    InstallPluginOp,
    LineMetadata,
    LineOp,
    NavigateToPageArgs,
    NavigateToPageOp,
    NavigateToScheduleArgs,
    NavigateToScheduleOp,
    ReplaceLineOp,
    ReplacePageArgs,
    ReplacePageOp,
    SettingCategory,
    SuggestVariablesArgs,
    SuggestVariablesOp,
    TaskItem,
    TaskStatus,
    ToolCall,
    ToolCallValidationError,
    TriggerSystemUpdateArgs,
    TriggerSystemUpdateOp,
    UninstallPluginArgs,
    UninstallPluginOp,
    UpdateCollectionArgs,
    UpdateCollectionOp,
    UpdateLineMetadataOp,
    UpdatePluginArgs,
    UpdatePluginConfigArgs,
    UpdatePluginConfigOp,
    UpdatePluginOp,
    UpdateScheduleArgs,
    UpdateScheduleOp,
    UpdateSettingArgs,
    UpdateSettingOp,
    UpdateTaskListArgs,
    UpdateTaskListOp,
    VariableSuggestion,
    parse_tool_call,
    supported_ops,
)

__all__ = [
    "_OP_REGISTRY",
    "Alignment",
    "ApplyPatchArgs",
    "ApplyPatchOp",
    "CreateCollectionArgs",
    "CreateCollectionOp",
    "CreateScheduleArgs",
    "CreateScheduleOp",
    "DayPattern",
    "DeleteLineOp",
    "DeleteScheduleArgs",
    "DeleteScheduleOp",
    "DisablePluginArgs",
    "DisablePluginOp",
    "EnablePluginArgs",
    "EnablePluginOp",
    "InsertLineOp",
    "InstallPluginArgs",
    "InstallPluginOp",
    "LineMetadata",
    "LineOp",
    "NavigateToPageArgs",
    "NavigateToPageOp",
    "NavigateToScheduleArgs",
    "NavigateToScheduleOp",
    "ReplaceLineOp",
    "ReplacePageArgs",
    "ReplacePageOp",
    "SettingCategory",
    "SuggestVariablesArgs",
    "SuggestVariablesOp",
    "TaskItem",
    "TaskStatus",
    "ToolCall",
    "ToolCallValidationError",
    "TriggerSystemUpdateArgs",
    "TriggerSystemUpdateOp",
    "UninstallPluginArgs",
    "UninstallPluginOp",
    "UpdateCollectionArgs",
    "UpdateCollectionOp",
    "UpdateLineMetadataOp",
    "UpdatePluginArgs",
    "UpdatePluginConfigArgs",
    "UpdatePluginConfigOp",
    "UpdatePluginOp",
    "UpdateScheduleArgs",
    "UpdateScheduleOp",
    "UpdateSettingArgs",
    "UpdateSettingOp",
    "UpdateTaskListArgs",
    "UpdateTaskListOp",
    "VariableSuggestion",
    "parse_tool_call",
    "supported_ops",
]
